# Generated by Django 3.2.4 on 2021-06-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_rename_database_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='term',
            field=models.DateTimeField(null=True),
        ),
    ]
