# Generated by Django 3.2.4 on 2021-07-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_alter_data_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='memo',
            field=models.TextField(null=True),
        ),
    ]
