# Generated by Django 3.2.4 on 2021-06-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_data_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='term',
            field=models.DateField(null=True),
        ),
    ]
